{% set name = "preprocess" %}
{% set version = "1.2.3" %}
{% set sha256 = "aa1d63ad0e424999c8fca107ef64340eae8967a64417463271311eef82073c49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/doconce/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - future

test:
  imports:
    - preprocess

about:
  home: https://github.com/doconce/preprocess
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'preprocess: a multi-language preprocessor'

  description: |
    Preprocess is like a typical C preprocessor, but it extends to multiple
    languages. Languages for which it works include: C++, Python,
    Perl, Tcl, XML, JavaScript, CSS, IDL, TeX, Fortran, PHP, Java, Shell
    scripts (Bash, CSH, etc.) and C#.
    Preprocess is usable both as a command line app and as a Python module.

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
