travis:
  secure:
    BINSTAR_TOKEN: IXinijl3Q9mlgtLVYbp+M3HGSbgE5M4UEkQTqcenrK7EpaLz2O9wcAUzJFp1nLZgWNKRkh/OVCJZ3KKoJux+IDDX5pBA+6ko62zjq4fQcG62LJXQPUV/UgrGJVawltkEJcun06/lYQtL2hX4bZPphF3yYS789MO4RFLazt7RiYxxyD1HE0XzWQltgcJvS/7mqT6nmtx0fp7ENeqG2wG/YZs3av03BInQl+VcbsQjPtMT24d7TQ+bYZ4FdTOQPWfqZGgmWD4oGLnUZkFUMCXkNCS8Urj1MEZo52dN9y8oufu2BuZRpd6943QB3iw8YbuN0ECCbaYEbF7LE2JSffu9d/frUfkCdjiUUHW6O0dobF7oasixQc9hV+Q7KS8TohrqVIkjY2qTGGRzF82QwPmbNcC+CFJIYz65n4WzhED89/WVWIOkUHlTvOfyvjBefkkkMKOy+jzcek+QGQlQaaxXkjQYnnw1OG4ae63tkBfLm99X7dTajS0wefZ7IocU0zRTOuk05IeUE0uUlny9Dh34KWc44Ff+QshiQ2CR+zPHa511Llz+J7elpJqlTAX8YGUIjPWBbsrw99Yj1VH4rPkHeOclx8npPytmcCBKTVN7l8F6OiEhsa5zFCfV6alXonIwsGP/+8HLJCimNi4Q6O31R7e2gW/b2gCJL6a07dmGVBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
