travis:
  secure:
    BINSTAR_TOKEN: cXwGIXsB881dxR80dOylvRzHIvVyO/CgJvHrqTIsO1zRy5EQ+wIgJ2fNa+V+CUMV1k8qkdbmt3bG08ht0IqhAsxuPiK+zEQ3m+duQXFPnv+fiaesYeXkkZHGbeHGuGvCyre98gFAG02fdVSyKap37aF8WnYoVTRYxavn1wzkQwv2KeVMS2c0alg6tE3N/Afn/tehapcwDjkuQg7RTCKEkQwwbS+RFuEUeC3JhH4OMWR9v2k2fFbzf19m9N1ekJmv42dmhOhaIVAZEJ5MkftXlpyu2LWUotkmPkI807aspWSjAOIfr1KUbkqAKatGGzSUF/qEoN0n/QpoDxk62dOMIYQWUKzpgPvRjgV1qDxyGiWHf8uW3GrrP9EHTMnKNmtiRTQcyRX1Bh9IEsHB/BVDB2AjNOzaqpBuo2ZjJi/Qc6bwPY1TkEPLKxfMdT6cP29CHJE6qdJ1p5bgG2XCIac9T8dXz5SU/tCRMs+zehOrwf/oXwKhshB9675eHOTj6U2K8aNTHPy9RcwVl8Qar8XusSnA89unQ1jPWsOyjwxdAKEyk74CHo2T7SI5SzCQZN6w+C8yMBr/KIWN2tSK8FSNX1YGOTK3qQ9bjS6C/300ZBbGPWKriuAUPjtoPf+Xy0bLtuMtGVdwdblhNdcIQp5AmWA1NOYXFbVqxK3/55ybzVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
